---
- name: Check and Restart Service on Windows
  hosts: windows_servers
  tasks:
    - name: Check if the service is running
      win_service:
        name: MyWindowsService
      register: service_status

    - name: Restart the service if it is stopped
      win_service:
        name: MyWindowsService
        state: started
      when: service_status.status != 'running' or service_status.start_mode != 'Auto'

    - name: Log service status to a file
      win_lineinfile:
        path: C:\temp\service_status.log
        line: "Service 'MyWindowsService' was found {{ service_status.status }} at {{ ansible_date_time.iso8601 }}."
        create: yes
