---
- name: Create a text file on Windows Server
  hosts: windows_servers
  tasks:
    - name: Create an empty text file
      win_file:
        path: C:\temp\example.txt
        state: touch

    - name: Write content to the text file
      win_lineinfile:
        path: C:\temp\example.txt
        line: "This is a sample content."
