---
- name: Test Windows connection with service management
  hosts: windows_servers
  gather_facts: yes
  collections:
      - ansible.windows
  tasks:
    - name: Check the status of the Windows Update service
      ansible.windows.win_service:
        name: wuauserv  
        state: started   
