---
- name: Install Notepad++ on Windows
  hosts: all
  tasks:
    - name: Copy Notepad++ installer to Windows host
      ansible.windows.win_copy:
        src: files/npp_installer.exe
        dest: C:\Temp\npp_installer.exe

    - name: Install Notepad++
      ansible.windows.win_shell:
        cmd: 'C:\Temp\npp_installer.exe /S'
