---
- name: Pre-check for windows
  hosts: windows_servers
  tasks:
    # ตรวจสอบบริการที่ระบุว่ามีอยู่หรือไม่
    - name: (Windows) Pre-check service ({{ service }})
      ansible.windows.win_service:
        name: "{{ service }}"  # ใส่เครื่องหมายคำพูดรอบตัวแปร service
      register: check_result
      when: ansible_facts['os_family'] == "Windows"

    # ตรวจสอบว่า Service มีอยู่หรือไม่และเก็บไว้ใน precheckservice
    - name: (Windows) Append if service exists
      set_fact:
        precheckservice: "{{ precheckservice | default([]) + [ service ] }}"
      when: check_result.exists == true

    # ตรวจสอบว่า Service หายไปและเก็บไว้ใน missing
    - name: (Windows) Append if service is missing
      set_fact:
        missing: "{{ missing | default([]) + [ service ] }}"
      when: check_result.exists == false

    # แสดงผลลัพธ์ที่ตรวจพบ
    - name: Show services that exist
      debug:
        msg: "The following services exist: {{ precheckservice }}"
      when: precheckservice | length > 0

    - name: Show services that are missing
      debug:
        msg: "The following services are missing: {{ missing }}"
      when: missing | length > 0
