---
- name: Pre-check for windows
  hosts: windows_servers
  tasks:
    # ดึงข้อมูลเกี่ยวกับบริการ (service) ทั้งหมดในเครื่อง
    - name: (Windows) Gather service facts
      ansible.windows.win_service_facts:

    # ตรวจสอบว่า Service มีอยู่หรือไม่
    - name: Check if service exists and append if exists
      set_fact:
        precheckservice: "{{ precheckservice | default([]) + [ service ] }}"
      when: "'{{ service }}' in ansible_facts.services"

    # ตรวจสอบว่า Service หายไปและเก็บข้อมูลบริการที่ขาดหายไป
    - name: Append if service is missing
      set_fact:
        missing: "{{ missing | default([]) + [ service ] }}"
      when: "'{{ service }}' not in ansible_facts.services"

    # แสดงผลลัพธ์ของการตรวจสอบ
    - name: Show services that exist
      debug:
        msg: "The following services exist: {{ precheckservice }}"
      when: precheckservice | length > 0

    - name: Show services that are missing
      debug:
        msg: "The following services are missing: {{ missing }}"
      when: missing | length > 0
