---
- name: Server Maintenance
  hosts: all

  # Loading the list of services and list of commands using relative paths
  vars_files:
    - services.yaml  # ใช้ relative path สำหรับ services.yaml
    - listcommand.yaml  # ใช้ relative path สำหรับ listcommand.yaml

  tasks:
    - name: Set Variable
      set_fact:
        precheckservice: []
        postcheckservice: []
        running: []
        missing: []

    - name: Check variable
      debug: var=inventory_hostname

    ### Pre-check service before reboot
    - name: Pre-check service before Reboot
      include_tasks: pre_check_services.yaml
      loop: "{{ services[inventory_hostname] }}"
      loop_control:
        loop_var: service
      ignore_errors: yes
      when: services[inventory_hostname] is defined

    ### Run command before reboot (non-Windows servers only)
    - name: Run command before reboot
      include_tasks: runcommand.yaml
      loop: "{{ commands[inventory_hostname] }}"
      loop_control:
        loop_var: command
      ignore_errors: yes
      when: ansible_facts['os_family'] != "Windows"

    ### Reboot the server
    - name: Reboot
      include_tasks: reboot.yaml

    ### Post-check service after reboot
    - name: Post-check service after Reboot
      include_tasks: post_check_services.yaml
      loop: "{{ services[inventory_hostname] }}"
      loop_control:
        loop_var: service
      ignore_errors: yes
      when: services[inventory_hostname] is defined

    ### Debug: Show pre-check services
    - name: Show pre-check services
      debug: var=precheckservice

    ### Debug: Show post-check services
    - name: Show post-check services
      debug: var=postcheckservice

    ### Summary
    - name: Summary
      debug:
        msg: >
          {% if precheckservice == postcheckservice %}
            OA {{ inventory_hostname }} has successfully passed.
          {% else %}
            Not pass:
              - All services: {{ services[inventory_hostname] }}
              - Running services: {{ postcheckservice }}
              - Missing services: {{ missing }}
          {% endif %}
      failed_when: "precheckservice != postcheckservice"

    ### Optional: Check if services.yaml and listcommand.yaml exist
    - name: Check if services.yaml file exists
      ansible.builtin.stat:
        path: "./services.yaml"  # ตรวจสอบว่าไฟล์ services.yaml มีอยู่ใน directory เดียวกัน
      register: services_file_status

    - name: Check if listcommand.yaml file exists
      ansible.builtin.stat:
        path: "./listcommand.yaml"  # ตรวจสอบว่าไฟล์ listcommand.yaml มีอยู่ใน directory เดียวกัน
      register: listcommand_file_status

    - name: Debug output for services.yaml file existence
      debug:
        msg: "services.yaml file exists: {{ services_file_status.stat.exists }}"

    - name: Debug output for listcommand.yaml file existence
      debug:
        msg: "listcommand.yaml file exists: {{ listcommand_file_status.stat.exists }}"
